# This is a basic workflow to help you get started with Actions

name: Web-Deployment

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install NPM and Cordova
        run: |
          cd sd-client
          sudo apt update
          sudo apt-get install nodejs npm
          sudo npm install -g cordova
        
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cd sd-client
          pwd
          cordova platform add browser
          cordova build browser
          ls platforms
          ls platform
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./platforms/browser/www
          destination_dir: ./app
          

